### ISSUE TITLE
Is there any way to use AutoPVS1 on hg38 data?

### ISSUE THREAD

**Issue by lourdesrosano** [JiguangPeng/autopvs1#10]
Hello,

From the tool's description and FAQ, it seems that AutoPVS1 is (only?) applicable to hg19 variants. We would like to confirm that this is indeed the case, and if it is, ask if there is any kind of workaround that would allow us to use this tool on hg38 data. Eg. maybe changing a few things at the source code or providing different reference data for VEP?

Thank you!

**Comment by JiguangPeng** [comment]
Yes,  AutoPVS1 is only applicable for hg19 in this version.
We are planning to upgrade AutoPVS1 to support both hg19 and hg38 genome in the next version.
Thanks for your feedback~

**Comment by lourdesrosano** [comment]
Hello again,
Thanks a lot for your quick answer! Do you have a rough time estimate of when this new version will be available?
Thank you.

**Comment by lourdesrosano** [comment]
Hello again @JiguangPeng,

As we need to use this tool rather soon, we have decided to go ahead and try to adapt AutoPVS1 to hg38 ourselves. After a (superficial) reviewing of the code, it looks like most of the required adaptations would involve using the hg38 version of the input files (and of course using the correct assembly when annotating with VEP).

However, we were wondering about the source of the following files (from `autopvs1/data/`):  `PM1.domain.bed, PM1.expert_curated.bed, PM1.hotspot.bed, PVS1.level`. As they do not seem to originate from a public database, we were wondering how you compiled these input files? If you would prefer, we could communicate in private via email.

We are looking forward to hearing back from you. Thank you!

**Comment by frSinger** [comment]
Dear JiguangPeng,

Thank you so much for making this tool available, it is of great help for the variant evaluation!

We are trying to use AutoPVS1 for hg38 variants instead of hg19, thus we are trying to upgrade the files provided to AutoPVS1 in "data" to the hg38 equivalents. 
However, for most of the files it is not clear to us how they were derived, so it would be great if you could provide some info on were the files come from and if they have been curated and if yes, in what fashion.
Any help is greatly appreciated.

Thank you in advance!

**Comment by JiguangPeng** [comment]
hi frSinger, sorry for the late reply, the hg38 supported version is coming soon~，in the middle of July

**Comment by frSinger** [comment]
Dear JiguangPeng,
Thank you, that is very good news!!
We are looking forward to the update, fingers crossed!

**Comment by JiguangPeng** [comment]
already support hg19 and hg38
